[package]
name = "conductor"
version = "0.1.0"
authors = ["Andrew Danger Lyon <orthecreedence@gmail.com>"]
edition = "2018"

[lib]
name = "conductor"
crate-type = ["dylib"]		# ["dylib", "staticlib"]
doctest = false				# these annoy me

[workspace]
members = []
exclude = []

[dependencies]
config = "0.9.2"
fern = "0.5.7"
lazy_static = "1.2.0"
log = "0.4.6"
postgres = "0.15.2"
quick-error = "1.2.2"
serde = "1.0.84"
time = "0.1.42"

