---
# logging configuration
logging:
  # the log level (ignore all messages with a log level lower than this)
  level: 'info'

# testing config
tests:
  # set these to a keypair (hex string), which can then be used to create a
  # superuser either via a client or via native tests. used to create users,
  # companies, and other objects with the flick of a wrist (great for setting
  # up test scenarios).
  bootstrap_user:
    pub: false
    sec: false

