consensus_public_key = "2b890d05f28750ed47b3d29ed9a221dc6978d12e1814d13f903fbceb7c7a0d00"
consensus_secret_key = "consensus.toml"
external_address = "127.0.0.1:6969"
listen_address = "0.0.0.0:6969"
service_public_key = "2ed65f5986e74641ab3ce8713b04750ae88552f208d93132f2b75143d295a21c"
service_secret_key = "service.toml"

[api]
private_api_address = "0.0.0.0:13008"
public_api_address = "0.0.0.0:13007"
state_update_timeout = 10000

[connect_list]
peers = []

[database]
create_if_missing = true
[[genesis.validator_keys]]
consensus_key = "2b890d05f28750ed47b3d29ed9a221dc6978d12e1814d13f903fbceb7c7a0d00"
service_key = "2ed65f5986e74641ab3ce8713b04750ae88552f208d93132f2b75143d295a21c"

[genesis.consensus]
first_round_timeout = 3000
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000
[mempool.events_pool_capacity]
api_requests_capacity = 1024
internal_events_capacity = 128
network_events_capacity = 512
network_requests_capacity = 512

[network]
max_incoming_connections = 128
max_outgoing_connections = 128
tcp_connect_max_retries = 10
tcp_connect_retry_timeout = 15000
tcp_nodelay = true
[services_configs.configuration_service]
