[common.consensus_config]
first_round_timeout = 3000
max_message_len = 1048576
max_propose_timeout = 200
min_propose_timeout = 10
peers_timeout = 10000
propose_timeout_threshold = 500
status_timeout = 5000
txs_block_limit = 1000

[common.general_config]
validators_count = 1

[common.services_config]

[node]
address = "127.0.0.1:6969"

[node.services_public_configs]

[node.validator_keys]
consensus_key = "e075824958382b0c79a9e5d0d785a193a17c3cf18023642d9b7a3c94e14700cd"
service_key = "3b9991f80804ca690ef7ccfb02a6a8be87abd89ec8e2fd5b7a9f197b6aa970b4"
